### ISSUE TITLE
Can't resolve 'array-move' 

### ISSUE THREAD

**Issue by Veerbhadra277** [samceracas/react-reorderable-list#1]
getting following error

./node_modules/react-reorderable-list/dist/index.modern.js
Module not found: Can't resolve 'array-move' in 'C:\Projects\example\node_modules\react-reorderable-list\dist'

I am using following package versions 

"react": "^16.14.0",
    "react-addons-update": "^15.6.2",
    "react-dom": "^16.14.0",
    "react-dropzone": "^5.1.1",
    "react-intl": "^2.7.2",
    "react-query-params": "^1.0.9",
    "react-redux": "^5.1.1",
    "react-reorderable-list": "^1.0.2",
    "react-router-bootstrap": "^0.24.4",
    "react-router-dom": "^4.3.1",
    "react-test-renderer": "^16.7.0",
    "react-toastify": "^4.5.2",
    "redux": "^3.7.2",
    "redux-mock-store": "^1.5.3",
    "redux-thunk": "^2.3.0",
    "typeface-roboto": "0.0.45"

**Comment by samceracas** [comment]
Fixed as of version v1.0.3 https://github.com/samceracas/react-reorderable-list/commit/eb060dee3fc7ed0de361e6e4219781a8d8268a71
